Repository cooldogepm/BedrockEconomy, pull requests merged in 2022-02, with the labels that each got.

#27 Support Vietnamese language
  resources/languages/vi-VN.yml
  src/cooldogedev/BedrockEconomy/language/LanguageManager.php
Labels: Category: UI

#28 Added Chinese translations
  resources/languages/zh-TW.yml
  src/cooldogedev/BedrockEconomy/language/LanguageManager.php
Labels: Category: UI

#30 Added Chinese translations (2nd pr)
  resources/languages/zh-CN.yml
  resources/languages/zh-TW.yml
  src/cooldogedev/BedrockEconomy/language/LanguageManager.php
Labels: Category: UI, Status: WIP

#47 Add Swissgerman Language (v2)
  resources/languages/de-CH.yml
  src/cooldogedev/BedrockEconomy/language/LanguageManager.php
Labels: Category: UI, Status: WIP

#48 Add Japanese translations
  resources/languages/ja-JP.yml
  src/cooldogedev/BedrockEconomy/language/LanguageManager.php
Labels: Category: UI, Status: Implemented
